/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#006389',
        'primary-container': '#097dac',
        'primary-fixed': '#c6e7ff',
        'primary-fixed-dim': '#82cfff',
        'on-primary': '#ffffff',
        'on-primary-container': '#fcfcff',
        'on-primary-fixed': '#001e2d',
        'on-primary-fixed-variant': '#004c6b',
        secondary: '#ac3323',
        'secondary-container': '#fd6e58',
        'secondary-fixed': '#ffdad4',
        'secondary-fixed-dim': '#ffb4a7',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6c0300',
        'on-secondary-fixed': '#400100',
        'on-secondary-fixed-variant': '#8a1a0e',
        tertiary: '#795500',
        'tertiary-container': '#996d00',
        'tertiary-fixed': '#ffdea8',
        'tertiary-fixed-dim': '#f9bc46',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        'on-tertiary-fixed': '#271900',
        'on-tertiary-fixed-variant': '#5e4200',
        surface: '#f7f9ff',
        'surface-dim': '#ccdcf0',
        'surface-bright': '#f7f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#edf4ff',
        'surface-container': '#e3efff',
        'surface-container-high': '#daeafe',
        'surface-container-highest': '#d4e4f8',
        'on-surface': '#0d1d2b',
        'on-surface-variant': '#3f484f',
        'inverse-surface': '#233241',
        'inverse-on-surface': '#e8f1ff',
        outline: '#6f787f',
        'outline-variant': '#bfc8d0',
        'surface-tint': '#00658d',
        'inverse-primary': '#82cfff',
        background: '#f7f9ff',
        'on-background': '#0d1d2b',
        'surface-variant': '#d4e4f8',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'deep-ink': '#1C2B3A',
      },
      fontFamily: {
        display: ['Bricolage Grotesque', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        baloo: ['Baloo 2', 'cursive'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        'margin-mobile': '20px',
        'margin-desktop': '40px',
        gutter: '16px',
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', fontWeight: '800' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '500' }],
        'label-mono': ['14px', { lineHeight: '1.0', fontWeight: '600', letterSpacing: '-0.02em' }],
      },
      animation: {
        'spring-in': 'springIn 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'spring-bounce': 'springBounce 2s infinite ease-in-out',
        'float': 'float 3s ease-in-out infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        springIn: {
          '0%': { opacity: '0', transform: 'scale(0.9) translateY(20px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        springBounce: {
          '0%, 100%': { transform: 'translateY(0) scale(1)' },
          '50%': { transform: 'translateY(-8px) scale(1.02)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
    },
  },
  plugins: [],
}
